/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersusRouteImport } from './routes/versus'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiScribeTokenRouteImport } from './routes/api/scribe-token'

const VersusRoute = VersusRouteImport.update({
  id: '/versus',
  path: '/versus',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScribeTokenRoute = ApiScribeTokenRouteImport.update({
  id: '/api/scribe-token',
  path: '/api/scribe-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/practice': typeof PracticeRoute
  '/versus': typeof VersusRoute
  '/api/scribe-token': typeof ApiScribeTokenRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/practice': typeof PracticeRoute
  '/versus': typeof VersusRoute
  '/api/scribe-token': typeof ApiScribeTokenRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/practice': typeof PracticeRoute
  '/versus': typeof VersusRoute
  '/api/scribe-token': typeof ApiScribeTokenRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battle'
    | '/practice'
    | '/versus'
    | '/api/scribe-token'
    | '/api/transcribe'
    | '/api/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/battle'
    | '/practice'
    | '/versus'
    | '/api/scribe-token'
    | '/api/transcribe'
    | '/api/tts'
  id:
    | '__root__'
    | '/'
    | '/battle'
    | '/practice'
    | '/versus'
    | '/api/scribe-token'
    | '/api/transcribe'
    | '/api/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleRoute: typeof BattleRoute
  PracticeRoute: typeof PracticeRoute
  VersusRoute: typeof VersusRoute
  ApiScribeTokenRoute: typeof ApiScribeTokenRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/versus': {
      id: '/versus'
      path: '/versus'
      fullPath: '/versus'
      preLoaderRoute: typeof VersusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scribe-token': {
      id: '/api/scribe-token'
      path: '/api/scribe-token'
      fullPath: '/api/scribe-token'
      preLoaderRoute: typeof ApiScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleRoute: BattleRoute,
  PracticeRoute: PracticeRoute,
  VersusRoute: VersusRoute,
  ApiScribeTokenRoute: ApiScribeTokenRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
